### ISSUE TITLE
现在的首页好别扭

### ISSUE THREAD

**Issue by darknessomi** [sdutlinux/SDUT-Devices#10]
@Ma233 少年，抽空把html 和静态文件改回sdut 分支啊，现在的这个首页好别扭，6号没法看啊。。。。

**Comment by zhwei** [comment]
哟，上线啦，给个链接

**Comment by darknessomi** [comment]
@zhwei 早就上线啦，http://210.44.176.204/

**Comment by darknessomi** [comment]
只不过现在上线的是公共版原来学校照片啥的都没了= =

**Comment by darknessomi** [comment]
@Ma233 s 少年，你再不改回去我就要报警了，PPT 上不是这样的。。。。。

**Comment by Ma233** [comment]
改改改...马上改 =w=
